apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-ibm-entitlement-key
spec:
  destination:
    namespace: cp4waiops
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4waiops/ibm-entitlement-key
    repoURL: https://github.com/gandhicloudlaborg/gan-sew-test8
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
